### ISSUE TITLE
rare: if we use  kdialog for wait_for only shows notification

### ISSUE THREAD

**Issue by mckaygerhard** [BashGui/easybashgui#24] opened 2024-02-17 05:25 UTC
this is weird, not to said others rare results:

if i set to dialog of course its reduced... cos cdialog is much better, but if i set to kdialog it only shows notification :laughing: 

![image](https://github.com/BashGui/easybashgui/assets/1571724/26b09419-4347-4417-904f-a0f9c34d801b)

this is just rare, i will investigate it

also after set, such notification shows again ramdonly, this is not iportant bug cos seems working.. but not as dessired! :smile: 

![image](https://github.com/BashGui/easybashgui/assets/1571724/a6497796-0e18-4406-aad5-b4a6ed2ccba3)

**Comment by vaisarger** [comment] 2024-02-17 12:44
Hi @mckaygerhard !

Unfortunately "kdialog" (despite is a KDE tool ) is one of more limited widget of EBG ones.
In fact, it has (or "had", I don't know if now this feature there is actually ) *not* a "wait" function.

The only function that seems (rather distantly ) a "wait" is the notification.
Unfortunately kdialog notification has a strange behavior: that is sometimes notifications are repeated several times.

In my opinion is a "bug" (?) related to kdialog.

if anyone could help me to undrstand better the issue, I would thank him very much...

**Comment by mckaygerhard** [comment] 2024-02-18 18:02
umm i used kdiualog from kde 3.X and that was not the behaviour.. who crap it become kdialog.. interesting.. 

ok lest leave this issue open by now.. maybe someone will found a better way to solve it or improve it.. (currently is working not perfect but works)

**Comment by vaisarger** [comment] 2024-02-29 15:03
Hi @mckaygerhard 

It could be useful, about this issue if you do this test (I don't have KDE )
- in a KDE desktop, in a terminal:
`source easybashgui
wait_for "This is a 40 sec test..."
sleep 40
terminate_wait_for`

-in a different desktop (GNOME, LXQt, whatever ), in a terminal:
`export supermode=kdialog
source easybashgui
wait_for "This is a 40 sec test..."
sleep 40
terminate_wait_for`

Let me know...

**Comment by vaisarger** [comment] 2024-03-28 10:09
I'm closing this issue for two reasons:
1) since Kdialog doesn't have any "wait_for"-like option, I used notification option (iterate every a certain amount of seconds -I remember 20 sec, hope i'm not wrong-; *so*... _it's normal_ to have a notification, every, let's say, 20 seconds... (not a bug)
2) a not normal behavior happens actually sometimes: all this notification are showed all together: this is not related to EBG though, it's related to system notification process instead (in fact, same issue appears even to different kind of notifications -e.g.: weather forecast, system notifications, etc. - )

**Closed by vaisarger** 2024-03-28 10:09 UTC

**Comment by mckaygerhard** [comment] 2024-03-29 20:18
ok no problem.. if someone has similar problem here will be a refence
